collections:
  authors:
    output: true
  posts:
    output: true
    permalink: /posts/:title/

javascript_enabled: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"