lang: ko-KR

timezone: Asia/Seoul

title: jychan99 blog

tagline: jychan update

name: Your New Jekyll Site

description: Blogging
meta_description: "Your New Jekyll Site, Blogging about stuffs"

url: "https://jychan99.github.io"

github:
  username: jychan99

social:
  links:
  - https://github.com/jychan99

google_site_verification: 000

google_analytics:
  id: '000'              # Google Analytics ID입니다. 이 또한 이후 포스팅에서 다루겠습니다.
  pv:           
    proxy_endpoint:   
    cache_path: 

toc: true 

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://jychan99.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
